name: Python Application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  run-databricks-job:
    runs-on: ubuntu-latest
    env:
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install Dependencies
      run: |
        pip install databricks-cli
    - name: Run Databricks Job on Existing Cluster
      id: databricks-job
      run: |
        export DATABRICKS_HOST=https://dbc-6cad2402-4428.cloud.databricks.com
        databricks jobs run-now --job-id 62667569273248
        
        run_output=$(databricks runs submit --job-id 62667569273248 --json-file job-parameters.json)
        run_id=$(echo "$run_output" | jq -r '.run_id')

    - name: Check Databricks Job Status
      run: |
          status=$(databricks runs get --run-id $run_id --query ExecutionStatus)
          
          if [ "$status" != "SUCCESS" ]; then
            echo "Databricks job failed."
            exit 1
          fi
        
